#!/bin/bash
# BEGIN_CONF
APP_DIR=ws
DB=/tmp/h2_bestdog
SQL_SCRIPT=bestdog/src/test/resources/db.sql
H2_DIR=bestdog/target/bestdog-1.0-SNAPSHOT/WEB-INF/lib/
JAVA_VERSION=java-7-oracle
JAVA_DIR=/usr/lib/jvm
MVN_DIR=/opt/java/maven
# END_CONF

ls $APP_DIR/
if [ $? -ne 0 ]; then
	echo "APP_DIR not found"
	exit -1
fi

# BEGIN_JAVA_CONF
JAVA_VERSION=java-7-oracle
JAVA_DIR=/usr/lib/jvm
MVN_DIR=/opt/java/maven
# END_JAVA_CONF

SCRIPTS_PATH="$PWD/scripts"

source $SCRIPTS_PATH/_jdk.sh $JAVA_VERSION $JAVA_DIR $MVN_DIR

cd $APP_DIR
# START_SCRIPT

java -cp $H2_DIR/h2*.jar org.h2.tools.RunScript -url jdbc:h2:$DB -script $SQL_SCRIPT
java -cp $H2_DIR/h2*.jar org.h2.tools.Server
