#!/bin/bash
# BEGIN_CONF
APP_DIR=ws
SQL_SCRIPT=bestdog/src/test/resources/db.sql
H2_DIR=bestdog/target/bestdog-1.0-SNAPSHOT/WEB-INF/lib/
DB=~/test
# END_CONF

ls $APP_DIR/
if [ $? -ne 0 ]; then
	echo "APP_DIR not found"
	exit -1
fi

cd $APP_DIR
# START_SCRIPT

$JAVA_HOME/bin/java -cp $H2_DIR/h2*.jar org.h2.tools.RunScript -url jdbc:h2:$DB -script $SQL_SCRIPT
$JAVA_HOME/bin/java -cp $H2_DIR/h2*.jar org.h2.tools.Server

