#!/bin/bash
# BEGIN_CONF
APP_DIR=bpel
TMP_ODE_DIR=/tmp/_ode
JAVA_VERSION=java-7-oracle
JAVA_DIR=/usr/lib/jvm
MVN_DIR=/opt/java/maven
ODE_WAR=$APP_DIR/ode/ode-1.3.6.zip
# END_CONF

ls $APP_DIR/
if [ $? -ne 0 ]; then
	echo "APP_DIR not found"
	exit -1
fi

# BEGIN_JAVA_CONF
JAVA_VERSION=java-7-oracle
JAVA_DIR=/usr/lib/jvm
MVN_DIR=/opt/java/maven
# END_JAVA_CONF

SCRIPTS_PATH="$PWD/scripts"

source $SCRIPTS_PATH/_jdk.sh $JAVA_VERSION $JAVA_DIR $MVN_DIR

# START_SCRIPT

rm -ri $TMP_ODE_DIR
mkdir $TMP_ODE_DIR
unzip $ODE_WAR -d $TMP_ODE_DIR

cd $APP_DIR

mvn tomcat7:run-war -Dmaven.tomcat.warDirectory=$TMP_ODE_DIR
